---
title: "Projections in Phylogeo"
date: "`r Sys.Date()`"
author: Zach Charlop-Powers
output: 
  rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Projections in Phylogeo}
  %\VignetteEngine{knitr::rmarkdown}
  \usepackage[utf8]{inputenc}
---

<link href="http://joey711.github.com/phyloseq/markdown.css" rel="stylesheet"></link>

```{r, message = FALSE, warning=FALSE, echo=FALSE}
#load knitr and set the default parameters
library("knitr")
opts_chunk$set(cache=TRUE, fig.width=6, message=FALSE, warning=FALSE, comment = "#>")
```

### Load Some Data
phylogeo uses the [mapproj](http://www.inside-r.org/packages/cran/mapproj/docs/mapproject) package to draw
its maps. This package supports a large number of projections and phylogeo supports nearly all of them as
demonstrated below.

```{r, message = FALSE, warning=FALSE}
library(phylogeo)
data(mountainsoil)
data(batmicrobiome)
data(epoxomicin_KS)
```

### Mercator Projection
```{r, message=FALSE, warning=FALSE}
#mercator() equally spaced straight meridians, conformal, straight compass courses
map_phyloseq(epoxomicin_KS)
map_phyloseq(epoxomicin_KS, projection="mercator")
map_network(epoxomicin_KS, projection="mercator", lines=TRUE, color="Geotype", jitter=TRUE)
map_tree(epoxomicin_KS, projection="mercator")
```

### Mollweide Projection
```{r, message=FALSE, warning=FALSE}
#mollweide() (homalographic) equal-area, hemisphere is a circle
map_phyloseq(epoxomicin_KS, projection="mollweide")
```

## Fisheye Projection
```{r, message=FALSE, warning=FALSE}
#fisheye(n) stereographic seen through medium with refractive index n
map_phyloseq(epoxomicin_KS, projection="fisheye", n=0.5)
```

### Albers Projection
```{r, message=FALSE, warning=FALSE}
#albers(lat0,lat1)equal-area, true scale on lat0 and lat1
map_phyloseq(epoxomicin_KS, projection="albers", lat0=20, lat1=70)
```
